### ISSUE TITLE
kochan c05

### ISSUE THREAD

**Issue by hakrdinesh** [hakrtech/vasanthv#1]

**Comment by hakrvasanth** [comment]
chapter 05 exercises completed

**Comment by hakrvasanth** [comment]
I'm working on example programs. eg01, Makefile completed and eg02 going on

**Comment by hakrvasanth** [comment]
working on example 03

**Comment by hakrvasanth** [comment]
working on example 04

**Comment by hakrvasanth** [comment]
working on example 05

**Comment by hakrvasanth** [comment]
working on example 06

**Comment by hakrvasanth** [comment]
working on example 07

**Comment by hakrvasanth** [comment]
working on example 08

**Comment by hakrvasanth** [comment]
working on final example program

**Comment by hakrdinesh** [comment]
Good work!
