### ISSUE TITLE
kochan c06

### ISSUE THREAD

**Issue by hakrdinesh** [hakrtech/vasanthv#2]

**Comment by hakrvasanth** [comment]
Now, I'm starting chapter 06

**Comment by hakrvasanth** [comment]
working on exercise 02

**Comment by hakrvasanth** [comment]
ex02 completed. now working on ex03

**Comment by hakrvasanth** [comment]
working on exercise 04

**Comment by hakrvasanth** [comment]
working on exercise 05

**Comment by hakrvasanth** [comment]
working on exercise 06

**Comment by hakrvasanth** [comment]
working on exercise ex06a

**Comment by hakrvasanth** [comment]
chapter 06 exercises all are completed.

**Comment by hakrvasanth** [comment]
Now, I'm start chapter 06 examples

**Comment by hakrvasanth** [comment]
working on example 04

**Comment by hakrvasanth** [comment]
working on example 05

**Comment by hakrvasanth** [comment]
working on example 06

**Comment by hakrvasanth** [comment]
working example 07

**Comment by hakrvasanth** [comment]
working on example 08

**Comment by hakrvasanth** [comment]
working on example 09

**Comment by hakrvasanth** [comment]
working on example 10

**Comment by hakrvasanth** [comment]
Lines of Code:   2683 (2054 non ws) in 71 files
Target LOC:      5000
Target Achieved: 53% (41%)

**Comment by hakrvasanth** [comment]
working on final example

**Comment by hakrvasanth** [comment]
Chapter 06 completed
