### ISSUE TITLE
kochan c07 - arrays

### ISSUE THREAD

**Issue by hakrdinesh** [hakrtech/vasanthv#3]

**Comment by hakrvasanth** [comment]
working with example 08

**Comment by hakrvasanth** [comment]
Chapter 07 all Examples completed.
now, i working on Exercises

**Comment by hakrvasanth** [comment]
working with exercise 03

**Comment by hakrvasanth** [comment]
working with exercise 04

**Comment by hakrvasanth** [comment]
working on exercise 05

**Comment by hakrvasanth** [comment]
working on exercise 06

**Comment by hakrvasanth** [comment]
working on exercise 07
