### ISSUE TITLE
kochan c08 - functions

### ISSUE THREAD

**Issue by hakrdinesh** [hakrtech/vasanthv#4]

**Comment by hakrvasanth** [comment]
ex03 square root
https://apod.nasa.gov/htmltest/gifcity/sqrt2.1mil
The square root of two = ?

**Comment by hakrvasanth** [comment]
please verify ex02

**Comment by hakrvasanth** [comment]
compile: gcc ex03a.c -o ex03 -lm
how to Makefile in ex03a?

**Comment by hakrdinesh** [comment]
:1st_place_medal:

**Comment by hakrdinesh** [comment]
:100:

**Comment by hakrdinesh** [comment]
:+1:

**Comment by hakrdinesh** [comment]
good work.
